DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS deployments;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS service_versions;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS nodes;
DROP EXTENSION IF EXISTS pgcrypto;
